application: wonkymindt86
version: 1b
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|mp3|wav))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|mp3|wav))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py
